---
- name: Listen for ServiceNow change Implement and run remediation
  hosts: all
  sources:
    - servicenow.itsm.records:
        table: change_request
        interval: 10
  rules:
    - name: Change moved to Implement
      condition: event.meta is defined
      action:
        debug:
          msg: "Event received TEST: {{ event }}"
