---
- name: Listen for ServiceNow change Implement and run remediation
  hosts: all
  sources:
    - servicenow.itsm.records:
        table: change_request
        interval: 10
        # Note on display values:
        # - Using display values makes payload fields human-readable but fragile (labels can change/localize).
        # - We intentionally match on stable internal identifiers (sys_id and choice value '-1').
        # - If you need labels for logging only, uncomment the line below.
        # display_value: true
  rules:
    - name: Change moved to Implement
      # Notes:
      # - ServiceNow 'state' is a choice-list; in many instances '-1' maps to the label 'Implement'.
      #   Confirm in your instance via sys_choice (table=change_request, element=state).
      # - 'assignment_group' below is a sys_id for stability. Use display_value only for logs.
      condition:
        all:
          - event.state == '-1'  # << Implement
          # - event.approval == 'approved'
          - event.assignment_group == '91b12d5b53c72610a33138f0a0490e52'  # << Event Driven Ansible
      action:
        debug:
          msg: |
            Implement detected:
            - number: {{ ansible_eda.event.number | default('') }}
            - sys_id: {{ ansible_eda.event.sys_id | default('') }}
            - state: {{ ansible_eda.event.state | default('') }}
            - approval: {{ ansible_eda.event.approval | default('') }}
            - assignment_group: {{ ansible_eda.event.assignment_group | default('') }}
