---

- name: Install Prometheus and Alertmanager with Alertmanager forwarder to ServiceNow
  hosts: prometheus-am
  become: true
  vars_files:
    - ../vault.yml
  vars:
    # Select forwarder mode: webhook | kafka | servicenow
    alertmanager_forwarder_mode: servicenow
    # Common forwarder settings
    alertmanager_forwarder_port: 9097
    alertmanager_repeat_interval: 1h
    # When mode == webhook
    #eda_webhook_url: https://EXAMPLE/eda-event-streams/.../post/
    #eda_event_stream_token: YOUR_TOKEN <<< Set in vault.yml
    # When mode == kafka
    #alertmanager_kafka_broker: broker1:9092
    #alertmanager_kafka_topic: alertmanager-alerts
    # When mode == servicenow
    servicenow_instance_url: https://dev282952.service-now.com
    servicenow_username: admin
    #servicenow_password: YOUR_PASSWORD <<< Set in vault.yml
  roles:
    - prometheus
    - alertmanager
